[Shell Search Provider]
# This file is placed at:
#   ~/.local/share/gnome-shell/search-providers/window-groups.ini
# It tells GNOME Shell about our search provider D-Bus service.

DesktopId=window-groups.desktop
BusName=com.github.window_groups.SearchProvider
ObjectPath=/com/github/window_groups/SearchProvider
Version=2
